version: "3.8"

services:
  foodapp:
    image: foodapp/foodapp:1.0.0
    secrets:
      - postgres-db-password
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/food_app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-db-password
      JAR_VERSION: 1.0.0
    ports:
      - 8080:8080
    depends_on:
      - postgres
    deploy:
      update_config:
        order: start-first
#    networks:
#      - spring-boot-foodapp

  foodapp-ui:
    image: foodapp/foodapp-ui:1.0.0
    ports:
      - 8081:80
    depends_on:
      - foodapp
    deploy:
      update_config:
        order: start-first
#    networks:
#      - spring-boot-foodapp
  postgres:
    image: postgres
    secrets:
      - postgres-db-password
    environment:
      POSTGRES_USER: red55
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-db-password
      PGDATA: /data/postgres
      POSTGRES_DB: food_app
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U red55 -d food_app"]
      interval: 15s
      timeout: 5s
      retries: 20
#    networks:
#      - spring-boot-foodapp

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
#    networks:
#      - spring-boot-foodapp
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
#    networks:
#      - spring-boot-foodapp
#networks:
#  spring-boot-foodapp:
#    driver: overlay
volumes:
  postgres:
  pgadmin:

secrets:
  postgres-db-password:
    external: true
