#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
server:
  port: 8080
spring:
  application:
    name: foodApp
  datasource:
    url: jdbc:postgresql://localhost:5332/food_app
    username: 'red55'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendingtesting123@gmail.com
    password: bepyqhcwxbrurnst #6K5ady)R
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true