services:
#  foodapp:
#    image: foodapp/foodapp:1.0.0
#    container_name: foodApp
#    environment:
#      DB_URL: jdbc:postgresql://postgres:5432/food_app
#      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-db-password
#      JAR_VERSION: 1.0.0
#    networks:
#      - postgres
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#  foodapp-ui:
#    image: foodapp/foodapp-ui:1.0.0
#    container_name: foodAppUI
#    networks:
#      - postgres
#    ports:
#      - 8081:80
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: red55
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    #      POSTGRES_DB: food_app
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
